apiVersion: v1
kind: ConfigMap
metadata:
  name: queue_addr
data:
  queue_addr: "192.168.1.10"
  queue_port: "5001"
  
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: judge
  namespace: judge
  labels:
    daemonset: judge
spec:
  selector:
    matchLabels:
      name: judge
  template:
    metadata:
      labels:
        name: judge
    spec:
      containers:
      - name: distributor
        image: distributor
        envFrom:
          - configMapRef:
              name: queue_addr
      - name: nodejs
        image: judge-nodejs
        resources:
          limits:
            memory: 4Gi
      - name: ruby
        image: judge-ruby
        resources:
          limits:
            memory: 4Gi
      - name: cpp
        image: judge-cpp
        resources:
          limits:
            memory: 4Gi
      - name: python
        image: judge-python
        resources:
          limits:
            memory: 4Gi
