// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dist-worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_nodejs Language = 0
	Language_ruby   Language = 1
	Language_python Language = 2
	Language_cpp    Language = 3
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "nodejs",
		1: "ruby",
		2: "python",
		3: "cpp",
	}
	Language_value = map[string]int32{
		"nodejs": 0,
		"ruby":   1,
		"python": 2,
		"cpp":    3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_dist_worker_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_dist_worker_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_dist_worker_proto_rawDescGZIP(), []int{0}
}

type JudgeInfo int32

const (
	JudgeInfo_ac  JudgeInfo = 0
	JudgeInfo_wa  JudgeInfo = 1
	JudgeInfo_ce  JudgeInfo = 2
	JudgeInfo_re  JudgeInfo = 3
	JudgeInfo_mle JudgeInfo = 4
	JudgeInfo_err JudgeInfo = 5
)

// Enum value maps for JudgeInfo.
var (
	JudgeInfo_name = map[int32]string{
		0: "ac",
		1: "wa",
		2: "ce",
		3: "re",
		4: "mle",
		5: "err",
	}
	JudgeInfo_value = map[string]int32{
		"ac":  0,
		"wa":  1,
		"ce":  2,
		"re":  3,
		"mle": 4,
		"err": 5,
	}
)

func (x JudgeInfo) Enum() *JudgeInfo {
	p := new(JudgeInfo)
	*p = x
	return p
}

func (x JudgeInfo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JudgeInfo) Descriptor() protoreflect.EnumDescriptor {
	return file_dist_worker_proto_enumTypes[1].Descriptor()
}

func (JudgeInfo) Type() protoreflect.EnumType {
	return &file_dist_worker_proto_enumTypes[1]
}

func (x JudgeInfo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JudgeInfo.Descriptor instead.
func (JudgeInfo) EnumDescriptor() ([]byte, []int) {
	return file_dist_worker_proto_rawDescGZIP(), []int{1}
}

type Submission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language     Language `protobuf:"varint,1,opt,name=language,proto3,enum=dist_worker.Language" json:"language,omitempty"`
	Code         string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	UserId       uint64   `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProblemId    uint64   `protobuf:"varint,4,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	SubmissionId uint64   `protobuf:"varint,5,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
}

func (x *Submission) Reset() {
	*x = Submission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_dist_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_dist_worker_proto_rawDescGZIP(), []int{0}
}

func (x *Submission) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_nodejs
}

func (x *Submission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Submission) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Submission) GetProblemId() uint64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *Submission) GetSubmissionId() uint64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

type JudgeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode JudgeInfo   `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=dist_worker.JudgeInfo" json:"result_code,omitempty"`
	Submission *Submission `protobuf:"bytes,2,opt,name=submission,proto3" json:"submission,omitempty"`
}

func (x *JudgeResult) Reset() {
	*x = JudgeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResult) ProtoMessage() {}

func (x *JudgeResult) ProtoReflect() protoreflect.Message {
	mi := &file_dist_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResult.ProtoReflect.Descriptor instead.
func (*JudgeResult) Descriptor() ([]byte, []int) {
	return file_dist_worker_proto_rawDescGZIP(), []int{1}
}

func (x *JudgeResult) GetResultCode() JudgeInfo {
	if x != nil {
		return x.ResultCode
	}
	return JudgeInfo_ac
}

func (x *JudgeResult) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidJob   bool        `protobuf:"varint,1,opt,name=valid_job,json=validJob,proto3" json:"valid_job,omitempty"`
	Submission *Submission `protobuf:"bytes,2,opt,name=Submission,proto3" json:"Submission,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_dist_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_dist_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetValidJob() bool {
	if x != nil {
		return x.ValidJob
	}
	return false
}

func (x *Job) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_worker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dist_worker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dist_worker_proto_rawDescGZIP(), []int{3}
}

var File_dist_worker_proto protoreflect.FileDescriptor

var file_dist_worker_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x69, 0x73, 0x74, 0x2d, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x22, 0xb0, 0x01, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x31, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x0b, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x37, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x73,
	0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5b, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x1b, 0x0a, 0x09, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x4a, 0x6f, 0x62, 0x12, 0x37, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x35, 0x0a, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x6a, 0x73,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x75, 0x62, 0x79, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x63, 0x70, 0x70, 0x10,
	0x03, 0x2a, 0x3d, 0x0a, 0x09, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x06,
	0x0a, 0x02, 0x61, 0x63, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x77, 0x61, 0x10, 0x01, 0x12, 0x06,
	0x0a, 0x02, 0x63, 0x65, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x72, 0x65, 0x10, 0x03, 0x12, 0x07,
	0x0a, 0x03, 0x6d, 0x6c, 0x65, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x10, 0x05,
	0x32, 0x79, 0x0a, 0x0c, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x37, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x17, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x4a, 0x6f, 0x62, 0x12, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x70,
	0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dist_worker_proto_rawDescOnce sync.Once
	file_dist_worker_proto_rawDescData = file_dist_worker_proto_rawDesc
)

func file_dist_worker_proto_rawDescGZIP() []byte {
	file_dist_worker_proto_rawDescOnce.Do(func() {
		file_dist_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_dist_worker_proto_rawDescData)
	})
	return file_dist_worker_proto_rawDescData
}

var file_dist_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dist_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dist_worker_proto_goTypes = []interface{}{
	(Language)(0),       // 0: dist_worker.Language
	(JudgeInfo)(0),      // 1: dist_worker.JudgeInfo
	(*Submission)(nil),  // 2: dist_worker.Submission
	(*JudgeResult)(nil), // 3: dist_worker.JudgeResult
	(*Job)(nil),         // 4: dist_worker.Job
	(*Empty)(nil),       // 5: dist_worker.Empty
}
var file_dist_worker_proto_depIdxs = []int32{
	0, // 0: dist_worker.Submission.language:type_name -> dist_worker.Language
	1, // 1: dist_worker.JudgeResult.result_code:type_name -> dist_worker.JudgeInfo
	2, // 2: dist_worker.JudgeResult.submission:type_name -> dist_worker.Submission
	2, // 3: dist_worker.Job.Submission:type_name -> dist_worker.Submission
	2, // 4: dist_worker.JudgeService.Submit:input_type -> dist_worker.Submission
	5, // 5: dist_worker.JudgeService.GetJob:input_type -> dist_worker.Empty
	5, // 6: dist_worker.JudgeService.Submit:output_type -> dist_worker.Empty
	4, // 7: dist_worker.JudgeService.GetJob:output_type -> dist_worker.Job
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dist_worker_proto_init() }
func file_dist_worker_proto_init() {
	if File_dist_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dist_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Submission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dist_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dist_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dist_worker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dist_worker_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dist_worker_proto_goTypes,
		DependencyIndexes: file_dist_worker_proto_depIdxs,
		EnumInfos:         file_dist_worker_proto_enumTypes,
		MessageInfos:      file_dist_worker_proto_msgTypes,
	}.Build()
	File_dist_worker_proto = out.File
	file_dist_worker_proto_rawDesc = nil
	file_dist_worker_proto_goTypes = nil
	file_dist_worker_proto_depIdxs = nil
}
